---
title: "Untitled"
author: "Alexander Strobel"
date: "3/10/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Method

We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study [cf. @Simmons2012]. 

```{r correlation, echo = F}
set.seed(242)
X = rnorm(64)
Y = .5 * X + rnorm(64)
cor_XY = cor.test(X[-1], Y[-1])
Pval <- function(p) {
  if (p < .001) { pchar = '$p<.001$' } 
  else { pchar = paste0('$p=', format(round(cor_XY$p.value, 3), nsmall = 3), '$') }
  return(pchar)
}

```

# Results

As hypothesized, X was correlated with Y, $r=$ `r sub("0.", ".", format(round(cor_XY$estimate, 2), nsmall = 2))`, $df=$ `r cor_XY$parameter`, `r Pval(cor_XY$p.value)`. 

```{r fig1, echo = F}
par(mfrow = c(1, 2))
# figure based on full data set
plot(X, Y, xlim = c(-3, 3), ylim = c(-3, 3), las = 1, main = "All Observations")
points(X[1], Y[1], pch = 19, col = 2)
abline(lm(Y ~ X), lwd = 1.5)
r = sub('.', '', format(round(cor(X, Y), 2), nsmall = 2))
text(2, -2.5, bquote(italic(r) == .(r)))
plot(X[-1], Y[-1], xlim = c(-3, 3), ylim = c(-3, 3), las = 1, main = "All Observations Except Case 1")
abline(lm(Y[-1] ~ X[-1]), lwd = 1.5)
r = sub('.', '', format(round(cor(X[-1], Y[-1]), 2), nsmall = 2))
text(2, -2.5, bquote(italic(r) == .(r)))
```